//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonMarket.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductCategory
    {
        public int Id { get; set; }
        public string ProductCategoryName { get; set; }
        public string ProductCategoryImgLargeUrl { get; set; }
        public string ProductCategoryImgSamllUrl { get; set; }
        public string ProductCategoryDesc { get; set; }
        public int DepartmentId { get; set; }
        public string Notes { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime UpdateDate { get; set; }
    }
}
